name: hexdump
description: A package to display binary data in a human-readable hexadecimal form.
version: 0.1.0
homepage: https://github.com/hacker1024/hexdump.dart

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
 collection: ^1.17.0

dev_dependencies:
  lint: ^2.0.1
